server:
  port: 8888
spring:
  application:
    name: bootcamp-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amatosg/configserver.git
          default-label: main
          timeout: 10